### ISSUE TITLE
Make sure npm publish publishes to @tilburg instead of unstable npm package

### ISSUE THREAD

**Issue by hansregeer** [nl-design-system/tilburg#82]
```
HttpErrorGeneral: 404 Not Found - PUT https://registry.npmjs.org/@tilburg%2fdesign-tokens - Not found
    at /home/runner/work/tilburg/tilburg/node_modules/.pnpm/npm-registry-fetch@17.0.1/node_modules/npm-registry-fetch/lib/check-response.js:95:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async publish (/home/runner/work/tilburg/tilburg/node_modules/.pnpm/libnpmpublish@9.0.7/node_modules/libnpmpublish/lib/publish.js:53:15)
    at async file:///home/runner/work/tilburg/tilburg/node_modules/.pnpm/p-pipe@4.0.0/node_modules/p-pipe/index.js:10:19
    at async file:///home/runner/work/tilburg/tilburg/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36 {
  name: 'ValidationError',
  headers: [Object: null prototype] {
    date: [ 'Fri, 26 Jul 2024 09:28:25 GMT' ],
    'content-type': [ 'application/json' ],
    'content-length': [ '21' ],
    connection: [ 'keep-alive' ],
    'cf-ray': [ '8a935c072d646458-SJC' ],
    vary: [ 'Accept-Encoding' ],
    server: [ 'cloudflare' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: [40](https://github.com/nl-design-system/tilburg/actions/runs/10108996902/job/27956048413#step:8:41)4,
  code: 'E404',
  method: 'PUT',
  uri: 'https://registry.npmjs.org/@tilburg%2fdesign-tokens',
  body: { error: 'Not found' },
  pkgid: '@tilburg/design-tokens@1.0.0-alpha.13'
}
```

https://github.com/nl-design-system/tilburg/actions/runs/10108996902/job/27956048413

**Comment by matijs** [comment]
Gefixt in #279 en #276
